-- tableの作成
create table users (
  id bigint generated by default as identity primary key,
  name text not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- カラムの追加
-- 追加するテーブルを指定
alter table users
add column new_column_name text;
-- row level securityを追加
alter table users enable row level security;
-- 名前
create policy "ポリシーの名前"
-- for ○○ で何を許可するかを決める
-- using (auth.uid() = user_id)でuidとuser_idが同じ場合、変更できる
on users for update using (auth.uid() = user_id);
